SCREEN_COLOR=(34,139,34)
BLACK=(0, 0, 0)
GREEN=(0,255,0)

BLOCK_SIZE=20
NUM_GRASS=20
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

FLAG_ROWS = 3
FLAG_COLS = 4
# game_field.py
flag_row = (BOARD_COLS - FLAG_COLS)* CELL_SIZE
flag_col = (BOARD_ROWS - FLAG_ROWS)* CELL_SIZE


MINE_ROWS = 1
MINE_COLS = 3
NUM_OF_MINES = 20

START_X_PLAYER = 0
START_Y_PLAYER = 0

LONG_PRESS_THRESHOLD = 1000

GUARD_START_ROW = (BOARD_ROWS // 2)*CELL_SIZE
GUARD_START_COL = 0

TRAP_COUNT = 5
TRAP_ROWS = 1
TRAP_COLS = 3
